apiVersion: v1
kind: Service
metadata:
  name: nginx-external-service
spec:
  selector:
    app: nginx-podname
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # or NodePort
